### ISSUE TITLE
ucd failed with coredump

### ISSUE THREAD

**Issue by mgonzal1** [clearlinux/micro-config-drive#47]
Deploying Clear Linux on baremetal using Openstack causes ucd core dump
Logs:
`
![image](https://user-images.githubusercontent.com/22683793/68345224-79754d80-00b6-11ea-9219-77a29cc6e441.png)

`

My user-data is:
`#cloud-config
package_upgrade: yes
packages:
  - java-runtime
  - git`

**Comment by ahkok** [comment]
Which version of micro-config-drive was this? There was a crash in a previous release that is currently fixed in `v43`

**Comment by mgonzal1** [comment]
I was using V42. I tested with V43 and it doesn't crash but it seems that network is not available to download packages:
`package_upgrade: Waited for network for 5 minutes, no answer - giving up.`

**Comment by ahkok** [comment]
> I tested with V43 and it doesn't crash but it seems that network is not available to download packages:

The method to look for an active connection uses a DNS request. If this fails then all subsequent `swupd` commands will also fail because they use the same DNS addresses to perform the software download.

Are you in a restricted network? Did networking work after the 5 minute timeout? Did the packages install correctly?

**Comment by ahkok** [comment]
I have one more fix. You'll need v44.

**Comment by ahkok** [comment]
No answer. Please check the thread and re-test if you can.
